name: loc
channels:
  - defaults
dependencies:
  - pandas=0.23.3
  - python=3.7
  - scikit-learn=0.19.1
  - statsmodels=0.9.0
  - pip:
    - black
    - doc8==0.8.0
    - flake8==3.5.0
    - flake8-bugbear==18.2.0
    - flake8-builtins==1.4.1
    - flake8-commas==2.0.0
    - flake8-comprehensions==1.4.1
    - flake8-deprecated==1.3
    - flake8-docstrings==1.3.0
    - flake8-eradicate
    - flake8-per-file-ignores==0.6
    - flake8-print==3.1.0
    - flake8-quotes==1.0.0
    - flake8-todo==0.7
    - matplotlib==2.2.2
    - nbsphinx==0.3.3
    - pep8-naming==0.7.0
    - pre-commit
    - pybtex==0.21
    - pytest==3.6.3
    - pytest-cov==2.5.1
    - pytest-pythonpath==0.7.2
    - sphinx==1.7.6
    - sphinx-rtd-theme==0.4.0
    - sphinxcontrib-bibtex==0.4.0
    - tox==3.1.3