name: loc
channels:
  - defaults
  - pscondaenvs
dependencies:
  - pscondaenvs=1.2.4
  - python=3.7
  - python-graphviz=0.8.4
  - scikit-learn=0.19.1
  - statsmodels=0.9.0
  - pip:
    - doc8==0.8.1
    - ipdb==0.13.2
    - jupyterlab==2.1.4
    - matplotlib==3.2.2
    - nbsphinx==0.7.1
    - pandas==1.0.5
    - pre-commit==2.5.1
    - pybtex==0.22.2
    - pytest==5.4.3
    - pytest-cov==2.10.0
    - pytest-pythonpath==0.7.3
    - restructuredtext_lint==1.3.1
    - sphinx==3.1.1
    - sphinx-rtd-theme==0.5.0
    - sphinxcontrib-bibtex==0.4.2
    - tox==3.7.0
