name: loc
channels:
  - defaults
dependencies:
  - pandas=0.23.3
  - python=3.7
  - python-graphviz=0.8.4
  - scikit-learn=0.19.1
  - statsmodels=0.9.0
  - pip:
    - black==18.9b0
    - doc8==0.8.0
    - flake8==3.7.5
    - flake8-bugbear==18.8.0
    - flake8-builtins==1.4.1
    - flake8-commas==2.0.0
    - flake8-comprehensions==2.0.0
    - flake8-deprecated==1.3
    - flake8-docstrings==1.3.0
    - flake8-eradicate==0.2.0
    - flake8-print==3.1.0
    - flake8-quotes==1.0.0
    - flake8-rst-docstrings==0.0.8
    - flake8-todo==0.7
    - flake8-type-annotations==0.1.0
    - matplotlib==3.0.2
    - nbsphinx==0.4.2
    - pep8-naming==0.8.2
    - pre-commit==1.14.4
    - pybtex==0.22.2
    - pytest==4.2.1
    - pytest-cov==2.6.1
    - pytest-pythonpath==0.7.3
    - sphinx==1.8.4
    - sphinx-rtd-theme==0.4.3
    - sphinxcontrib-bibtex==0.4.2
    - tox==3.7.0