name: loc
channels:
  - defaults
dependencies:
  - numpy=1.14.2
  - pandas=0.22.0
  - python=3.6.5
  - scikit-learn=0.19.1
  - statsmodels=0.8.0
  - pip:
    - matplotlib==2.2.2
    - sphinx==1.7.4
    - tox==3.0.0