#! python


def build(ctx):

    ctx.recurse('pre_analysis_plan')
    ctx.recurse('data_preparation')
    ctx.recurse('analysis')
    ctx.recurse('figures')

    # Safety measure -- else the LaTeX scanner might fail because some
    # '.tex'-source file has not been generated.
    ctx.add_group()
    ctx.recurse('paper')
    # ctx.recurse('documentation')
