def build(ctx):

    ctx.recurse("pre_analysis_plan")
    ctx.recurse("data_preparation")
    ctx.recurse("analysis")
    ctx.recurse("figures")

    ctx.add_group()

    ctx.recurse("paper")
    # ctx.recurse('documentation')

    from src.figures.project_dependency_graph import make_dot_file

    ctx.add_pre_fun(make_dot_file)
